version: '3.7'

services:
  # Previous services remain unchanged
  accounts:
    image: "accounts-ms:1.0"
    container_name: accounts-ms
    ports:
      - "8082:8080"
    networks:
      - backend

  loans:
    image: "loans-ms:1.0"
    container_name: loans-ms
    ports:
      - "8081:8080"
    networks:
      - backend

  gateway:
    image: "go-gateway:1.0"
    container_name: gateway-ms
    ports:
      - "8080:8080"
    networks:
      - backend

  postgres:
    image: "postgres:14"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "lol"
      POSTGRES_USER: "postgres"
    networks:
      - backend

  prometheus:
    image: "prom/prometheus:v2.43.0"
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - backend

  # Adding Loki service
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - backend

  # Adding Promtail service
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - backend

networks:
  backend:
    driver: bridge
